### PR TITLE
Update class.apiengine.php

### PR DESCRIPTION
**Pull request by xDaizu**
Hotfixed function name problem that caused everything to go awfully wrong.

### CODE REVIEW

**Comment by kasperisager** [comment]
Functions in PHP are not case sensitive which makes me wonder why this is causing issues on your end.

**Comment by xDaizu** [comment]
I think it's because it's not actually calling a function, but parsing a string (see library/core/class.request.php, line 9)

**Comment by kasperisager** [comment]
True; the regex used for matching method names is however also case-insensitive: https://github.com/vanilla/vanilla/blob/2.1/library/core/class.request.php#L124

Needless to say, this has never been a problem on my end so I'm very interested as to why it seems to be on yours.

**Comment by xDaizu** [comment]
I think I found the problem. I'm afraid the code you linked is not updated (though it led me in the right direction). 
You linked code from 2.1 (and this api actually only works in 2.2). In the version 2.2.3.6 the regex is not case insensitive:

https://github.com/vanilla/vanilla/blob/Vanilla_2.2.3.6/library/core/class.request.php#L127

**Comment by kasperisager** [comment]
Ah! The tagged releases of the 2.2 branch are pretty old; the regex has been fixed on the current master (2.2.100) and 2.1 branches.

**Comment by xDaizu** [comment]
Oh, I see... my bad, then (?). Master had an unknown bug that prevented it from installing in my environment, so I went for the tagged one.

Boy oh boy I'm waiting for them to oficially release the 2.2... -.-

**Comment by kasperisager** [comment]
Putting this here for posterity: https://github.com/vanilla/vanilla/commit/213cc3807242204d77c07f52512206418e365fd3

**Pull request closed without merging**
